---
- name: Set Up Lab Environment
  hosts: nodes
  become: true
  tasks:
    - name: Ensure docker is installed
      apt:
        name:
          - docker.io
        state: latest

    - name: Ensure docker compose is installed
      apt:
        name:
          - docker-compose
        state: latest

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: Reset SSH connection to allow group to be picked up
      ansible.builtin.meta: reset_connection 

    - name: Add user to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        state: present
        append: yes
      become: true 

